### ISSUE TITLE
Publish pretrained model not only in baidu.

### ISSUE THREAD

**Issue by MyLtYkRiTiK** [ujsyehao/mobilenetv3-ssd#10]
Can you please provide pretrained models not only in baidu? It is impossible to download it for foreign users.

As an option you can send it via mail to me and I publish it in google disk.

**Comment by ujsyehao** [comment]
@okay, I provide a google drive link

**Comment by MyLtYkRiTiK** [comment]
Thank you very much!

Hope it is possible to provide .pth model too.

**Comment by shreymohan** [comment]
Hey, can you please provide the .pth files on google drive? Baidu is not working for us. Thank you!
