### ISSUE TITLE
Model FPS

### ISSUE THREAD

**Issue by MyLtYkRiTiK** [ujsyehao/mobilenetv3-ssd#12]
Do you have good FPS of your model?
I get only 35 fps on 1080 card.
But i have more than 50 fps on ssd with mobilenetV2.

**Comment by ujsyehao** [comment]
Do you use PyTorch model or ncnn model on 1080?
I have tested mv3-ssd ncnn model speed on phones.

**Comment by MyLtYkRiTiK** [comment]
I use pytorch model.
I suppose that ssd on mobilenetv3 should be faster than on mobilenetv2.
But I can't get the same results.

**Comment by ujsyehao** [comment]
This is my results on 1070ti
mobilenetv3-ssd 51.6fps 
mobilenetv2-ssd 48.8fps
