### ISSUE TITLE
Could you please provide a train script?

### ISSUE THREAD

**Issue by PointCloudNiphon** [ujsyehao/mobilenetv3-ssd#14]
Can you provide a train script? I am really new here and want to train my model with my own dataset, So could you please provide a train script? And I am curious about how to modify .param manually(add priorbox layer, detection_output layer, etc.)?

**Comment by ujsyehao** [comment]
1. You can refer to [mmdetection](https://github.com/open-mmlab/mmdetection/), I have provided the [script](https://github.com/ujsyehao/mobilenetv3-ssd/blob/master/pytorch_model/ssd300_mobilenetv3_pascal.py)

2. You can refer to my provide *.param
