### ISSUE TITLE
pytorch版本？

### ISSUE THREAD

**Issue by hexins** [ujsyehao/mobilenetv3-ssd#16]
请问下您用的pytorch版本和mmdetection版本是多少？
我试了下转换出来的.param文件跟您给出的不大一样，我转换出来的文件头上没有那一大堆MemoryData指令，有点怀疑是pytorch版本不一样，我用的pytorch是1.2.0, mmdetection是1.1.0
附上我的param文件：
[ncnn.param.txt](https://github.com/ujsyehao/mobilenetv3-ssd/files/4705702/ncnn.param.txt)

**Comment by ujsyehao** [comment]
pytorch1.1
mmdetection unsure version
