### ISSUE TITLE
小目标检测有什么设置建议吗。

### ISSUE THREAD

**Issue by yangtianyu92** [ujsyehao/mobilenetv3-ssd#17]
作者用的mmdetection和pytorch版本，mmdetection应该是v1.0rc0（重要，1.0，0.6, 1.2， 2+都是不行的）, pythorch是1.1

**Comment by yangtianyu92** [comment]
这里再分享下，作者的mobilenetv3.py放 mmdetection/mmdet/models/backbones, 记得改__init__.py， 把类型导入。
作者提供的mobilenetv3_ssd_head.py放mmdetection/mmdet/models/anchor_heads， 记得改__init__， 把类型导入。
训练的话，如果内存在400G，修改shm-size后直接 python train.py ssd300_mobilenetv3_pascal.py -- gpus 8，低于200G内存的就不要开那么多GPU训练了。。

**Comment by yangtianyu92** [comment]
最后我用作者提供的训练文件，在未改动情况下训练出来的pth模型文件是37M，百度网盘下载的是27M。。。。这。。

**Comment by ujsyehao** [comment]
pytorch模型和mmdetection版本我已不再维护, 这个repo主要是提供mobilenetv3-ssd转ncnn，你上述３个问题我简单回答下:

- "模型不管用，检测人还行，检测商标logo不行" 这个模型本来就是在VOC上训练的，VOC类别里有商标这一类？训练集都不包含商标怎么检测的出来
- 你这个400G或者200G应该都是开了docker后的虚拟内存吧
- 37M > 27M，这个你得去pytorch和mmdetection下提issue,模型体积变大我也不清楚原因

**Comment by yangtianyu92** [comment]
> pytorch模型和mmdetection版本我已不再维护, 这个repo主要是提供mobilenetv3-ssd转ncnn，你上述３个问题我简单回答下:
> 
> * "模型不管用，检测人还行，检测商标logo不行" 这个模型本来就是在VOC上训练的，VOC类别里有商标这一类？训练集都不包含商标怎么检测的出来
> * 你这个400G或者200G应该都是开了docker后的虚拟内存吧
> * 37M > 27M，这个你得去pytorch和mmdetection下提issue,模型体积变大我也不清楚原因

1.LOGO检测我用自己的LOGO数据集重新训练的啊，我把mmdetection所有版本都安装试了一遍才把训练跑通。pytorch所有官方镜像我都全了。
2.内存问题只是用mmdetection训练中出现的，如果谁要用自己数据集训练的话，给一个提示。
3.模型大小真的对不上，我对着找的，你自己pth模型是27m，用的是mobilenetV3-small的吧，但是你代码里给的是mobilenetV3-large的，那个下下来就是38，怎么可能训出来个27m的。。。

# model settings
input_size = 300
model = dict(
    type='SingleStageDetector',
    pretrained='./snapshots/mbv3_large.old.pth.tar',
    backbone=dict(
        type='MobileNetV3_Large',
		ssd_body=True
        ),
