### ISSUE TITLE
How to find the covert.py

### ISSUE THREAD

**Issue by zhoujinhai** [ujsyehao/mobilenetv3-ssd#2]
Convert mobilenetv3-ssd pytorch model to ncnn framework, Can you provide the code? Thanks

**Comment by ujsyehao** [comment]
It is split into several parts. Which parts do you want? ex: pytorch to onnx? onnx to ncnn?

**Comment by zhoujinhai** [comment]
Thanks, I have tried my pth model to onnx, then onnx convert to ncnn, but I can't get predict any thing, can you share the pth to onnx and onnx to ncnn code with me If you are convenient?

**Comment by ujsyehao** [comment]
1. pytorch -> onnx: I use mmdetection detection framework, the code you can refer to mmdetection
2. onnx -> ncnn: just use ./onnx2ncnn *.onnx new.param new.bin
