### ISSUE TITLE
Target_means and target_stds values.

### ISSUE THREAD

**Issue by MyLtYkRiTiK** [ujsyehao/mobilenetv3-ssd#8]
Hello!
I have a question why are your target_means and target_stds are (0) and (1)?

https://github.com/ujsyehao/mobilenetv3-ssd/blob/ec5bfcf29b50629561343c3a0a330814bd142517/pytorch_model/mobilenetv3_ssd_head.py#L26

**Comment by ujsyehao** [comment]
It is coordinates' means and variance, I set target_means = (0, 0, 0, 0) and target_stds = (0.1, 0.1, 0.2, 0.2) in mobilenetv3-ssd config.py
